[package]
name = "concurrent_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
rand = "0.8.5"
rayon = "1.7.0"
tokio = { version="1.32.0", features=['full'] }
